# schema: https://github.com/bienzaaron/berry/blob/master/packages/docusaurus/static/configuration/yarnrc.json

compressionLevel: mixed

enableGlobalCache: false

# ノードパッケージのインストール方法を定義します。
nodeLinker: node-modules

# npm レジストリにおけるパッケージバージョンの公開日付から算出される、インストール対象として考慮するための最小経過時間（分単位）です。
npmMinimalAgeGate: 20160 # 2 weeks

# パッケージゲートから除外するパッケージ記述子の配列またはパッケージ名のグロブパターン。
npmPreapprovedPackages:
  - vite
  - sass
