CREATE DATABASE IF NOT EXISTS `sp`
    DEFAULT CHARSET = utf8mb4
    DEFAULT COLLATE = utf8mb4_general_ci;

CREATE USER 'sp'@'%' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON *.* TO 'cna'@'%' WITH GRANT OPTION;
